### ISSUE TITLE
Ship PDB/CIF input files as part of the asapdiscovery-data package

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#187]
In order to run tests and provide examples, we need to be able to include some binary files (oedu, npy, etc) as well as large files (pdb, cif, sdf, csv) as a part of our repo. @ijpulidos has been very cautious about this as it results in GitHub keeping track of wayyyy too many changes.

We need some way to be able to ship these files as a part of the repo!

**Comment by kaminow** [comment]
could we potentially have links to some AWS bucket?

**Comment by dotsdl** [comment]
Let's proceed with a similar approach as we're taking for pulling model weights in `asapdiscovery.ml`; we can host the artifacts on a public AWS S3 bucket, and give the examples API in `asapdiscovery.data.examples`.

**Comment by apayne97** [comment]
do you have a protocol for how to set this up? happy to do it but not sure how

**Comment by hmacdope** [comment]
If we can detail what the metadata for each download is I can whip up a setup similar to the one for the ML weights. 

Here is an example of the YAML for the weights. 
```yaml
gat_test_v0:
  type: GAT
  base_url: https://asap-discovery-ml-weights.s3.amazonaws.com/test/
  weights:
    resource: gat_example.pth
    sha256hash: 38e5476ede0ed67ad0951d5d1c7c913ecf0aeaa6a1913d16ee9dca28b5d9795b
  config:
    resource: gat_example_config.json
    sha256hash: d0b4d6c1f74b3e9caacea50af6ff6927803143842a72e74ebc7dbefdb2bcf444
  last_updated: 2023-01-01
```
If we need them to be some kind of coherent set or unit we can have a base level identifier (`model`) in this case. Otherwise we can just have a list of files and `sha256hash`.

```yaml
file1: blah
  resource: blah
  sha256hash: blahblahblahblah
file2: 
  resource: blah
  sha256hash: blahblahblahblah
```

You will also need to point me to the exact files we want and I (or someone else with S3 keys) can upload them.
